[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "winclear"
version = "0.1.0"
description = "Clear stdout on Windows command prompt"
readme = "README.md"
requires-python = ">=3.9"

[project.scripts]
winclear = "clear:main"
